Ab#110903 parameterizing pipeline deploy
nathangiusti/Power-BI-Pipeline-Deploy pull request #3
Opened 2022-03-11 21:26 UTC by ravicyberman

Moved tenant_id = sys.argv[3]  #P3 above 

resp = requests.get('[https://login.microsoftonline.com/{}/oauth2/token](https://login.microsoftonline.com/%7B%7D/oauth2/token)'.format(tenant_id), data=data)

To resolve error: UnboundLocalError: local variable 'tenant_id' referenced before assignment

2022-03-11 23:21 UTC, nathangiusti requested changes

2022-03-11 23:21 UTC, nathangiusti commented on README.md
> +name: 'Power BI Pipeline Deploy'
Take this sample action.yaml out. 

Think about the difference between the action.yaml file and the workflow yaml file. The action yaml.file describes the action. The workflow yaml file is what is what people actually create to use the action. We want to include a sample workflow.

2022-03-11 23:21 UTC, nathangiusti commented on scripts/pipeline_deploy.py
> +from ast import arg
Do we need this?

2022-03-11 23:21 UTC, nathangiusti commented on scripts/pipeline_deploy.py
> +import argparse
You can comment this out if you wanna take shot at the arg parse stuff later.

2022-03-11 23:21 UTC, nathangiusti commented on scripts/pipeline_deploy.py
>  #tenant_id = 'cef04b19-7776-4a94-b89b-375c77a8f936'
Go ahead delete these commented lines.

2022-03-11 23:38 UTC, ravicyberman commented on README.md
> +name: 'Power BI Pipeline Deploy'
Got it so, I'll the actions.yaml out and leave the Deploy to prod workflow sample part in there as it is very similar to my Deploy to test.yaml

2022-03-11 23:41 UTC, ravicyberman commented on scripts/pipeline_deploy.py
> +import argparse
Yup, planning to use argparse in my next stint.

2022-03-12 00:06 UTC, ravicyberman commented on scripts/pipeline_deploy.py
> +from ast import arg
don't think so as they doesn't seem to be any parse() used in the code according this doc:
https://www.educative.io/edpresso/what-is-astargarg-annotation-typecomment-in-python

2022-03-12 22:26 UTC, nathangiusti requested changes

2022-03-12 22:26 UTC, nathangiusti commented on scripts/pipeline_deploy.py
> +
remove the extra white space as well.

2022-03-14 13:21 UTC, nathangiusti approved these changes

2022-03-14 14:36 UTC, merged